### PR TITLE
Adds gallery component.

### PR DESCRIPTION
**Pull request by HeyItsFelipe**
Adds gallery component.
To view on Home page, uncomment line 21 in home.js.

### CODE REVIEW

**Comment by VelazquezLuis** [comment]
Reviewed code, Gallery data added

**Comment by VelazquezLuis** [comment]
Seems I choose merge thinking it was reviewing.

**Review by robscafe433 — COMMENTED** [review]
Reviewed code, will look at code more closely, especially line 21 to understand how it works.

**Comment by robscafe433** [comment]
Reviewed code, will look at code more closely especially line 21 to understand how it works.

**Pull request merged**
